server:
  port: 4242
  servlet.context-path: '/api'

huza:
  owner-role-name: owner

spring:
  application:
    name: huza

management:
  endpoints:
    web:
      base-path: '/actuator'
      exposure.include: '*'


