server:
  port: 4242
  servlet.context-path: '/'

huza:
  owner-role-name: owner

spring:
  application:
    name: huza

  web.resources.static-locations: 'classpath:/static/'
  mvc.static-path-pattern: '/**'

management:
  endpoints:
    web:
      base-path: '/api/actuator'
      exposure.include: '*'
