huza:
  api-url: 'http://localhost:4242/api/'
  file-storage-path: .temp/2023-02-14/tmp.2023-02-14-05-16-53/huza-files

spring:

  datasource:
    name: 'huza-datasource'
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/huza'
    username: 'huza'
    password: 'huza'

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:4242/api/auth/realms/huza
#          jwk-set-uri: http://localhost:4242/api/auth/realms/huza/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  private-key: 'key.pem'
  public-key: 'cert.pem'
  type: 'JWT'
  issuer: 'ITMO 160RXTX Team'
  audience: '160RXTX Backend'
